name: web_extension_info
description:
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  intl: any
  meta: any
  logger: any

  synchronized: any
  
  pshondation:
    git:
      url: https://github.com/pshonkaaa/package.pshondation.dart.git

  # WEB
  # ------------------------------------------------------------------------------------------
  web_window_api:
    git:
      url: https://github.com/pshonkaaa/package.web_window_api.web.dart.git

  web_chrome_api:
    git:
      url: https://github.com/pshonkaaa/package.web_chrome_api.web.dart.git

  web_communication:
    git:
      url: https://github.com/pshonkaaa/package.web_communication.web.dart.git
  # ------------------------------------------------------------------------------------------